export const siteContent = {
  navigation: [
    { href: "/services", key: "services" },
    { href: "/portfolio", key: "work" },
    { href: "/about", key: "about" },
    { href: "/pricing", key: "pricing" },
  ],
  heroCards: [
    { title: "Pedes Terserah", big: true, image: "/portfolio/pedes-terserah.webp", link: "https://pedesterserah.vercel.app/" },
    { title: "Gendewo", big: false, image: "/portfolio/gendewo.webp", link: "https://gendewo-sigma.vercel.app/" },
    { title: "ALW Studio", big: false, image: "/portfolio/alw-studio.webp", link: "https://alwctudio.vercel.app" },
  ],
  marquee: ["Next.js", "✦", "TypeScript", "✦", "React", "✦", "Product UI", "✦", "Web Apps", "✦", "API Integrations", "✦", "Database Systems", "✦", "Responsive Design", "✦"],
  contact: {
    whatsapp: "https://wa.me/6285716275034",
    phone: "+62 857 1627 5034",
    email: "agencyalw@gmail.com",
    instagram: "https://www.instagram.com/alwgen/",
    linkedin: "https://www.linkedin.com/in/alw-bruh-638311286/",
    location: "Wonosobo, Central Java",
  },
  about: {
    values: [
      { title: "Honest", desc: "We tell you what we think, not what you want to hear. If we're not the right fit, we'll say so." },
      { title: "Fast", desc: "We respect your time. No endless back-and-forth. Most projects are live in 2–3 weeks." },
      { title: "Quality-first", desc: "We build things the right way. Clean code, real performance, tested across all devices." },
      { title: "Long-term", desc: "We're not here to deliver one project and disappear. We build relationships, not just websites." },
    ],
    story: [
      "Alw Agency was born in Wonosobo, a small city in Central Java, Indonesia — with a simple belief: that small and medium businesses deserve the same quality of digital products as the big players.",
      "We started building websites for local businesses who were tired of overpriced agencies that delivered generic templates. We grew by being reliable, fast, and genuinely invested in our clients' success.",
      "Today, we work with SMBs across Indonesia and internationally — from local service businesses needing a professional online presence, to growing e-commerce stores, to teams that need custom software to run their operations.",
      "We're a small, focused team. That means direct communication, real accountability, and zero bureaucracy. When you work with us, you talk to the people actually building your product.",
    ],
    stats: [
      { value: "3+", label: "Years building" },
      { value: "10+", label: "Projects delivered" },
      { value: "4", label: "Core services" },
      { value: "∞", label: "Cups of coffee" },
    ],
    techStack: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL", "Prisma", "Tailwind CSS", "Vercel", "Stripe", "Figma"],
  },
  services: [
    { id: "company-profile", num: "01", title: "Company Profile Website", tagline: "Your digital storefront, done right.", desc: "A professional digital home that builds trust instantly. We craft beautiful, fast-loading, mobile-first websites that make the right impression on every visitor — whether they find you on Google or arrive from a referral.", details: ["Custom design tailored to your brand", "5–15 pages depending on package", "Fully mobile responsive", "SEO-optimised from day one", "CMS integration (edit your content easily)", "Google Analytics & Search Console setup", "Fast delivery — 1 to 3 weeks"], tags: ["Next.js", "SEO-ready", "CMS", "Mobile-first"], from: "$499" },
    { id: "ecommerce", num: "02", title: "E-Commerce & Online Store", tagline: "Sell more. Manage less.", desc: "Full-featured online stores with everything you need to sell successfully: product management, payment integration, order tracking, and analytics. Built on proven platforms, customised to your business.", details: ["Product catalog & inventory management", "Payment gateway integration (Stripe, PayPal, local options)", "Multi-currency support", "Order management & fulfilment", "Customer accounts & wishlists", "Promo codes & discount engine", "Detailed sales analytics"], tags: ["Payment gateway", "Inventory", "Analytics", "Multi-currency"], from: "$1,500" },
    { id: "systems", num: "03", title: "Internal Business Systems", tagline: "Software built for your workflow.", desc: "Custom web applications for your internal team — data management dashboards, automated reports, HR tools, inventory tracking, CRM systems. We replace spreadsheets and manual processes with clean, fast software.", details: ["Role-based access control", "Custom database design", "Automated reporting & exports", "API integrations with existing tools", "Real-time data updates", "Admin dashboard", "Mobile-friendly UI"], tags: ["Custom logic", "Role-based access", "Reporting", "API integrations"], from: "Custom" },
    { id: "landing", num: "04", title: "Landing Page & Funnel", tagline: "One page. One goal. Maximum conversions.", desc: "High-converting pages for product launches, ad campaigns, events, or lead generation. Every element is purposefully placed to guide visitors toward a single action — whether that's buying, signing up, or getting in touch.", details: ["Conversion-focused copywriting guidance", "Fast load time (Core Web Vitals optimised)", "A/B testing ready", "Lead capture & CRM integration", "Countdown timers & urgency elements", "Heatmap & analytics integration", "Mobile-first, pixel-perfect"], tags: ["A/B ready", "Fast load", "Analytics", "Lead capture"], from: "$499" },
  ],
  plans: [
    { tier: "Starter", name: "Launch", price: "$499", per: "one-time", desc: "For new businesses that need a professional online presence, fast.", features: ["Up to 5 pages", "Mobile-responsive design", "Contact form & WhatsApp button", "Basic SEO setup", "Google Analytics integration", "1 round of revisions", "2-week delivery"], featured: false, cta: "Get started" },
    { tier: "Most Popular", name: "Growth", price: "$1,200", per: "one-time", desc: "For established SMBs ready to compete online with a complete digital presence.", features: ["Up to 15 pages", "Custom design system", "CMS integration (editable content)", "Full SEO & schema markup", "Performance optimised", "Blog / news section", "3 rounds of revisions", "3-week delivery"], featured: true, cta: "Get started" },
    { tier: "Custom", name: "Scale", price: "Custom", per: "scoped project", desc: "E-commerce, SaaS MVP, internal systems, or complex requirements.", features: ["E-commerce or custom web app", "Payment gateway integration", "Custom business logic", "API integrations", "Admin dashboard", "Ongoing support plan", "Timeline based on scope"], featured: false, cta: "Discuss your project" },
  ],
  pricingFaqs: [
    { q: "How long does it take to build a website?", a: "Most company profile websites take 1–2 weeks. E-commerce projects typically take 3–5 weeks. Custom business systems vary based on complexity." },
    { q: "Do you work with international clients?", a: "Yes. We work with SMBs globally. Our team communicates in English and handles all time zones via async collaboration." },
    { q: "What happens after the website is launched?", a: "We stay available after launch for questions and small fixes. For ongoing maintenance and updates, we offer retainer plans." },
    { q: "Do you offer payment plans?", a: "Yes. We typically ask for 50% upfront and 50% on completion. For larger projects, we can discuss milestone-based payments." },
    { q: "Can I upgrade my package later?", a: "Absolutely. Many clients start with Launch and upgrade to Growth as their business grows. We make migration seamless." },
    { q: "What if I need something not in the packages?", a: "Contact us and describe your project. We'll give you an honest quote based on your specific needs." },
  ],
  faqs: [
    { q: "How much does a website cost?", a: "Pricing starts at $499 for a Focused Sprint — a tightly scoped marketing site with a clear brief and fast turnaround. Most product builds (e-commerce, custom features, integrations) start around $1,200. Larger custom apps, MVPs, and long-term engineering work are scoped individually since the range depends on complexity." },
    { q: "How long does a project take?", a: "A Focused Sprint typically ships in 1–2 weeks. A Product Build usually takes 3–5 weeks depending on scope. Custom web apps and integrations vary more — you'll get a realistic timeline after the Frame the Problem step, before any code is written." },
    { q: "What's the difference between a Marketing Website and a Custom Web App?", a: "A Marketing Website is built to explain your product and convert visitors — fast, expressive, and focused on trust and clarity. A Custom Web App is an internal tool, dashboard, or business system built around how your team actually works, not a generic template. Not sure which one you need? Tell us the problem you're solving and we'll recommend the right scope." },
    { q: "Do you build e-commerce stores?", a: "Yes. E-commerce builds include product flows, checkout and payment integrations, inventory, CMS, and analytics — built to make day-to-day selling simpler, not just to look good." },
    { q: "Can you help me build an MVP quickly?", a: "Yes — that's what the MVPs & Experiments service is for. We help you turn an idea into a working first version fast, so you can test the concept with real users before committing to a full build." },
    { q: "What technologies do you use?", a: "Next.js, TypeScript, and React for the frontend, with databases, authentication, and API integrations built to match the project. The stack is picked based on what the product actually needs, not a one-size-fits-all template." },
    { q: "What does your process look like?", a: "Four steps: Frame the problem, Shape the experience, Build in the open, and Ship & improve." },
    { q: "Do I need to provide the content myself?", a: "Not necessarily — tell us what you have and what you don't. We can work from existing brand materials or help shape the content and structure as part of the build." },
    { q: "Do you work with clients outside Indonesia?", a: "Yes. Alw Agency is based in Wonosobo, Indonesia, and works with SMBs worldwide. All communication and delivery is remote-friendly." },
    { q: "How do I get started?", a: "Share the problem, the product, or even a rough idea through the contact form. You'll get a practical next step and an honest view of what it'll take to build." },
  ],
} as const;