export const siteContent = {
  seo: {
    title: "ALW Gen - Jasa Pembuatan Website Profesional di Indonesia",
    description: "Jasa pembuatan website profesional di Indonsia, Jawa Tengah, Wonosobo. Spesialis company profile, e-commerce, landing page, dan sistem bisnis custom.",
    keywords: ["jasa pembuatan website indonesia", "web development agency", "jasa website company profile", "jasa landing page", "jasa e-commerce agency", "software house jawa tengah"],
  },
  navigation: [
    { href: "/services", key: "services" },
    { href: "/portfolio", key: "work" },
    { href: "/about", key: "about" },
    { href: "/pricing", key: "pricing" },
  ],
  heroCards: [
    { title: "Pedes Terserah", big: true, image: "/portfolio/pedes-terserah.webp", link: "https://pedesterserah.vercel.app/" },
    { title: "Gendewo", big: false, image: "/portfolio/gendewo.webp", link: "https://gendewo-sigma.vercel.app/" },
    { title: "ALW Studio", big: false, image: "/portfolio/alw-studio.webp", link: "https://alwctudio.vercel.app" },
  ],
  marquee: ["Next.js", "✦", "TypeScript", "✦", "React", "✦", "Product UI", "✦", "Web Apps", "✦", "API Integrations", "✦", "Database Systems", "✦", "Responsive Design", "✦"],
  contact: {
    whatsapp: "https://wa.me/6285716275034",
    phone: "+62 857 1627 5034",
    email: "agencyalw@gmail.com",
    instagram: "https://www.instagram.com/alwgen/",
    linkedin: "https://www.linkedin.com/in/alw-bruh-638311286/",
    location: "Wonosobo, Central Java",
  },
  about: {
    values: [
      { title: "Honest", desc: "We tell you what we think, not what you want to hear. If we're not the right fit, we'll say so." },
      { title: "Fast", desc: "We respect your time. No endless back-and-forth. Most projects are live in 2–3 weeks." },
      { title: "Quality-first", desc: "We build things the right way. Clean code, real performance, tested across all devices." },
      { title: "Long-term", desc: "We're not here to deliver one project and disappear. We build relationships, not just websites." },
    ],
    story: [
      "Alw Agency was born in Wonosobo, a small city in Central Java, Indonesia — with a simple belief: that small and medium businesses deserve the same quality of digital products as the big players.",
      "We started building websites for local businesses who were tired of overpriced agencies that delivered generic templates. We grew by being reliable, fast, and genuinely invested in our clients' success.",
      "Today, we work with SMBs across Indonesia and internationally — from local service businesses needing a professional online presence, to growing e-commerce stores, to teams that need custom software to run their operations.",
      "We're a small, focused team. That means direct communication, real accountability, and zero bureaucracy. When you work with us, you talk to the people actually building your product.",
    ],
    stats: [
      { value: "3+", label: "Years building" },
      { value: "10+", label: "Projects delivered" },
      { value: "4", label: "Core services" },
      { value: "∞", label: "Cups of coffee" },
    ],
    techStack: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL", "Prisma", "Tailwind CSS", "Vercel", "Stripe", "Figma"],
  },
  services: [
    { id: "company-profile", num: "01", title: "Company Profile Website", tagline: "Rumah digital profesional yang membangun kepercayaan.", desc: "Desain modern, loading cepat, mobile-first, dan dibuat untuk kesan pertama yang tepat.", details: ["Custom design sesuai brand", "Sampai 15 halaman", "Mobile responsive", "SEO-ready", "CMS integration", "Google Analytics"], tags: ["Next.js", "SEO-ready", "CMS", "Mobile-first"], from: "Rp 298.000" },
    { id: "ecommerce", num: "02", title: "E-Commerce & Toko Online", tagline: "Toko online lengkap untuk mengubah pengunjung menjadi pelanggan.", desc: "Kelola produk, pembayaran, pesanan, dan analitik dalam satu toko online yang dirancang sesuai bisnis Anda.", details: ["Product catalog & inventory", "Payment gateway", "Order management", "Multi-currency", "Analytics", "Promo codes"], tags: ["Payment gateway", "Inventory", "Analytics", "Multi-currency"], from: "Custom" },
    { id: "systems", num: "03", title: "Sistem Bisnis Internal", tagline: "Software yang mengikuti alur kerja tim Anda.", desc: "Aplikasi web custom untuk manajemen data, laporan, HR, inventory, dan operasional yang lebih rapi.", details: ["Role-based access", "Custom database", "Automated reporting", "API integrations", "Admin dashboard", "Mobile-friendly UI"], tags: ["Custom logic", "Role-based access", "Reporting", "API integrations"], from: "Custom" },
    { id: "landing", num: "04", title: "Landing Page & Funnel", tagline: "Satu halaman. Satu tujuan. Konversi maksimal.", desc: "Halaman berkonversi tinggi untuk produk, campaign, event, atau lead generation.", details: ["Conversion-focused structure", "Fast load time", "A/B testing ready", "Lead capture", "Analytics integration", "Mobile-first"], tags: ["A/B ready", "Fast load", "Analytics", "Lead capture"], from: "Rp 298.000" },
  ],
  plans: [
    { tier: "Promo", name: "Coba Dulu", price: "Gratis", per: "7 minggu pertama", desc: "Coba website atau landing page berjalan selama 7 minggu tanpa biaya, tanpa DP.", features: ["1 halaman website", "Desain responsive", "Free trial 7 minggu", "Tanpa kartu kredit / DP", "Bisa lanjut kapan saja"], featured: true, cta: "Coba Gratis Sekarang" },
    { tier: "Focused sprint", name: "Launch", price: "Rp 298.000", per: "mulai dari, per project", desc: "Website fokus dengan scope ringkas dan jalur cepat menuju launch.", features: ["Sampai 5 halaman", "Desain mobile-responsive", "Form kontak & WhatsApp", "Setup SEO dasar", "Google Analytics", "1x revisi", "Estimasi 2 minggu"], featured: false, cta: "Mulai Sekarang" },
    { tier: "Product build", name: "Growth", price: "Rp 2.500.000", per: "mulai dari, per project", desc: "Build lebih mendalam untuk tim yang butuh kehadiran digital khas dan ruang untuk berkembang.", features: ["Sampai 15 halaman", "Desain sistem custom", "Integrasi CMS", "SEO & schema lengkap", "Performa dioptimasi", "Section blog / berita", "3x revisi", "Estimasi 3 minggu"], featured: false, cta: "Mulai Sekarang" },
    { tier: "Long-term partner", name: "Scale", price: "Hubungi Kami", per: "custom / scoped project", desc: "Untuk aplikasi custom, MVP, integrasi, dan produk yang butuh engineering matang.", features: ["E-commerce atau aplikasi custom", "Integrasi payment gateway", "Business logic custom", "API integrations", "Admin dashboard", "Support berkelanjutan", "Timeline sesuai scope"], featured: false, cta: "Diskusikan Project" },
  ],
  pricingFaqs: [
    { q: "How long does it take to build a website?", a: "Most company profile websites take 1–2 weeks. E-commerce projects typically take 3–5 weeks. Custom business systems vary based on complexity." },
    { q: "Do you work with international clients?", a: "Yes. We work with SMBs globally. Our team communicates in English and handles all time zones via async collaboration." },
    { q: "What happens after the website is launched?", a: "We stay available after launch for questions and small fixes. For ongoing maintenance and updates, we offer retainer plans." },
    { q: "Do you offer payment plans?", a: "Yes. We typically ask for 50% upfront and 50% on completion. For larger projects, we can discuss milestone-based payments." },
    { q: "Can I upgrade my package later?", a: "Absolutely. Many clients start with Launch and upgrade to Growth as their business grows. We make migration seamless." },
    { q: "What if I need something not in the packages?", a: "Contact us and describe your project. We'll give you an honest quote based on your specific needs." },
  ],
  faqs: [
    { q: "How much does a website cost?", a: "Pricing starts at $499 for a Focused Sprint — a tightly scoped marketing site with a clear brief and fast turnaround. Most product builds (e-commerce, custom features, integrations) start around $1,200. Larger custom apps, MVPs, and long-term engineering work are scoped individually since the range depends on complexity." },
    { q: "How long does a project take?", a: "A Focused Sprint typically ships in 1–2 weeks. A Product Build usually takes 3–5 weeks depending on scope. Custom web apps and integrations vary more — you'll get a realistic timeline after the Frame the Problem step, before any code is written." },
    { q: "What's the difference between a Marketing Website and a Custom Web App?", a: "A Marketing Website is built to explain your product and convert visitors — fast, expressive, and focused on trust and clarity. A Custom Web App is an internal tool, dashboard, or business system built around how your team actually works, not a generic template. Not sure which one you need? Tell us the problem you're solving and we'll recommend the right scope." },
    { q: "Do you build e-commerce stores?", a: "Yes. E-commerce builds include product flows, checkout and payment integrations, inventory, CMS, and analytics — built to make day-to-day selling simpler, not just to look good." },
    { q: "Can you help me build an MVP quickly?", a: "Yes — that's what the MVPs & Experiments service is for. We help you turn an idea into a working first version fast, so you can test the concept with real users before committing to a full build." },
    { q: "What technologies do you use?", a: "Next.js, TypeScript, and React for the frontend, with databases, authentication, and API integrations built to match the project. The stack is picked based on what the product actually needs, not a one-size-fits-all template." },
    { q: "What does your process look like?", a: "Four steps: Frame the problem, Shape the experience, Build in the open, and Ship & improve." },
    { q: "Do I need to provide the content myself?", a: "Not necessarily — tell us what you have and what you don't. We can work from existing brand materials or help shape the content and structure as part of the build." },
    { q: "Do you work with clients outside Indonesia?", a: "Yes. Alw Agency is based in Wonosobo, Indonesia, and works with SMBs worldwide. All communication and delivery is remote-friendly." },
    { q: "How do I get started?", a: "Share the problem, the product, or even a rough idea through the contact form. You'll get a practical next step and an honest view of what it'll take to build." },
  ],
} as const;