"use client";

import Link from "next/link";
import { useLanguage } from "./LanguageProvider";
import { siteContent } from "@/lib/content";

const copy = {
  id: {
    badge: "Digital Solution Partner", title: "Kami Bantu Bisnis Anda Tumbuh Lewat Teknologi", subtitle: "ALW Gen adalah software house yang membangun website, aplikasi web, dan solusi digital custom untuk bisnis yang ingin naik kelas secara online.", primary: "Konsultasi Gratis", servicesCta: "Lihat Layanan", location: "Wonosobo, Jawa Tengah", trustTitle: "Dipercaya oleh berbagai bisnis dari berbagai sektor", servicesTitle: "Layanan Kami", servicesSub: "Solusi digital lengkap untuk kebutuhan bisnis Anda, dari website sederhana hingga sistem custom.", whyTitle: "Kenapa Pilih ALW Gen", whySub: "Kami bukan sekadar vendor, tapi partner digital jangka panjang untuk bisnis Anda.", processTitle: "Proses Kerja Kami", processSub: "Alur kerja yang terstruktur dari awal konsultasi hingga project Anda live.", portfolioTitle: "Karya Terbaik Kami", portfolioSub: "Beberapa project yang telah kami kerjakan untuk klien dari berbagai industri.", portfolioCta: "Lihat Semua Portfolio", pricingTitle: "Paket Harga", pricingSub: "Pilih paket sesuai kebutuhan bisnis Anda. Transparan, tanpa biaya tersembunyi.", trialBanner: "Coba Dulu 7 Minggu — Gratis, Tanpa Ribet!", trialNote: "Pakai dulu, rasakan hasilnya selama 7 minggu tanpa bayar. Baru lanjut kalau puas.", testimonialsTitle: "Apa Kata Klien Kami", testimonialsSub: "Kepuasan klien adalah prioritas utama kami.", techTitle: "Teknologi yang Kami Gunakan", techSub: "Tools dan framework modern untuk hasil yang cepat, aman, dan scalable.", faqTitle: "Pertanyaan yang Sering Diajukan", finalTitle: "Siap Wujudkan Project Digital Anda?", finalSub: "Konsultasikan kebutuhan website atau aplikasi Anda sekarang, gratis tanpa komitmen.", finalCta: "Konsultasi Sekarang", whatsapp: "Chat via WhatsApp", aboutTitle: "Tentang ALW Gen", aboutText: "ALW Gen adalah software house berbasis di Wonosobo, Jawa Tengah, yang fokus membantu bisnis membangun kehadiran digital melalui website dan aplikasi custom. Kami mengutamakan kualitas, kecepatan, dan komunikasi yang jelas di setiap project.", aboutCta: "Selengkapnya Tentang Kami", blogTitle: "Insight & Artikel Terbaru", blogSub: "Tips dan wawasan seputar dunia digital dan pengembangan web.", comingSoon: "Segera hadir.",
    stats: [["20+", "Project Selesai"], ["10+", "Klien Puas"], ["3+", "Tahun Pengalaman"], ["98%", "On-Time Delivery"]],
    services: [["Web Development", "Pembuatan website company profile, landing page, hingga sistem web custom dengan performa cepat dan SEO-friendly."], ["E-Commerce Solution", "Toko online lengkap dengan sistem pembayaran, manajemen stok, dan dashboard admin yang mudah digunakan."], ["UI/UX Design", "Desain antarmuka yang menarik dan mudah digunakan, fokus pada pengalaman pengguna dan tingkat konversi."], ["Custom Software / Web App", "Aplikasi internal untuk manajemen operasional bisnis, sesuai kebutuhan spesifik perusahaan Anda."], ["SEO & Digital Presence", "Optimasi website agar mudah ditemukan di Google dan strategi meningkatkan visibilitas brand secara online."], ["Maintenance & Support", "Pemeliharaan rutin, update keamanan, dan dukungan teknis agar website selalu berjalan optimal."]],
    reasons: [["Proses Cepat & Efisien", "Timeline pengerjaan jelas dan realistis, tanpa mengorbankan kualitas hasil akhir."], ["Harga Transparan", "Tidak ada biaya tersembunyi. Semua rincian disampaikan di awal sebelum project berjalan."], ["Support Setelah Launching", "Kami tetap mendampingi setelah website live, bukan lepas tangan begitu project selesai."], ["Teknologi Modern", "Menggunakan stack terkini untuk performa cepat dan aman jangka panjang."]],
    steps: [["Discovery", "Diskusi kebutuhan, target, dan goals bisnis Anda untuk menentukan solusi yang tepat."], ["Design", "Pembuatan desain UI/UX sesuai brand identity dan pengalaman pengguna yang optimal."], ["Development", "Proses coding dengan update progress berkala agar Anda selalu tahu status project."], ["Testing", "Pengujian menyeluruh dari sisi fungsi, performa, dan kompatibilitas perangkat."], ["Launch", "Website atau aplikasi resmi diluncurkan dan siap digunakan."], ["Support", "Pendampingan pasca-launching, maintenance rutin, dan bantuan teknis berkelanjutan."]],
    plans: [["Coba Dulu", "Gratis", "7 minggu pertama", "Coba website atau landing page berjalan selama 7 minggu tanpa biaya.", ["1 halaman website", "Desain responsive", "Free trial 7 minggu", "Tanpa kartu kredit / DP"]], ["Starter", "Rp 298.000", "mulai dari, per project", "Untuk landing page atau website sederhana dengan kebutuhan dasar.", ["1-3 halaman", "Desain responsive", "Domain & hosting", "Optimasi SEO dasar"]], ["Business", "Hubungi Kami", "sesuai kebutuhan", "Untuk company profile, e-commerce, atau sistem custom dengan fitur lengkap.", ["Multi-halaman / custom pages", "Integrasi database", "Panel admin/CMS", "Support pasca-launching"]]],
    faqs: [["Berapa lama waktu pengerjaan website?", "Landing page umumnya 3-7 hari, company profile 1-2 minggu, dan sistem custom 3-8 minggu."], ["Apakah ada garansi setelah website selesai?", "Ya, kami memberikan garansi bug fixing gratis selama periode tertentu setelah website live."], ["Bagaimana sistem pembayaran project?", "DP 30% di awal project, lalu pelunasan 70% setelah project selesai dan sebelum website di-launch."], ["Apakah website akan dioptimasi untuk SEO?", "Ya, setiap website menerapkan dasar SEO on-page seperti kecepatan loading, struktur heading, dan meta tag."], ["Apakah ALW Gen melayani klien di luar Wonosobo?", "Ya, kami melayani klien dari seluruh Indonesia secara remote."], ["Bagaimana cara memulai project?", "Hubungi kami via form kontak atau WhatsApp untuk sesi konsultasi gratis."]],
    testimonials: [["Budi Santoso", "Owner, Retail Nusantara", "Tim ALW Gen sangat responsif dan hasil websitenya melebihi ekspektasi kami."], ["Sari Wulandari", "Marketing Manager, Glow Skincare", "Landing page yang dibuat langsung meningkatkan konversi penjualan kami."], ["Ahmad Fauzi", "Direktur, Konsultan Prima Advisory", "Proses kerja jelas, komunikasi lancar, dan hasil akhir sesuai harapan."]],
  },
  en: {
    badge: "Digital Solution Partner", title: "We Help Your Business Grow Through Technology", subtitle: "ALW Gen is a software house building websites, web apps, and custom digital solutions for businesses ready to move up online.", primary: "Free Consultation", servicesCta: "View Services", location: "Wonosobo, Central Java", trustTitle: "Trusted by businesses across many industries", servicesTitle: "Our Services", servicesSub: "Complete digital solutions for your business, from simple websites to custom systems.", whyTitle: "Why Choose ALW Gen", whySub: "We are not just a vendor, but your long-term digital partner.", processTitle: "Our Workflow", processSub: "A structured process from the first consultation until your project goes live.", portfolioTitle: "Our Best Work", portfolioSub: "A selection of projects built for clients across different industries.", portfolioCta: "View All Portfolio", pricingTitle: "Pricing Packages", pricingSub: "Choose a package for your business. Transparent, with no hidden fees.", trialBanner: "Try It First for 7 Weeks — Free, No Hassle!", trialNote: "Use it and see the results for seven weeks at no cost. Continue only when you are happy.", testimonialsTitle: "What Our Clients Say", testimonialsSub: "Client satisfaction is our top priority.", techTitle: "Technology We Use", techSub: "Modern tools and frameworks for fast, secure, scalable results.", faqTitle: "Frequently Asked Questions", finalTitle: "Ready to Build Your Digital Project?", finalSub: "Discuss your website or app needs with us, free with no commitment.", finalCta: "Get a Consultation", whatsapp: "Chat via WhatsApp", aboutTitle: "About ALW Gen", aboutText: "ALW Gen is a software house based in Wonosobo, Central Java, helping businesses build their digital presence through websites and custom applications.", aboutCta: "More About Us", blogTitle: "Latest Insights & Articles", blogSub: "Tips and insights about the digital world and web development.", comingSoon: "Coming soon.",
    stats: [["20+", "Projects Completed"], ["10+", "Happy Clients"], ["3+", "Years Experience"], ["98%", "On-Time Delivery"]],
    services: [["Web Development", "Company profiles, landing pages, and custom web systems with fast performance and SEO-ready foundations."], ["E-Commerce Solution", "Online stores with payments, inventory management, and easy-to-use admin dashboards."], ["UI/UX Design", "Attractive, intuitive interfaces focused on user experience and conversion."], ["Custom Software / Web App", "Internal applications for business operations, tailored to your company."], ["SEO & Digital Presence", "Website optimization and strategies to improve your brand visibility online."], ["Maintenance & Support", "Routine maintenance, security updates, and technical support to keep your website healthy."]],
    reasons: [["Fast & Efficient Process", "Clear, realistic timelines without compromising the final quality."], ["Transparent Pricing", "No hidden fees. Every detail is shared before the project begins."], ["Post-Launch Support", "We stay with you after launch instead of disappearing when the project ends."], ["Modern Technology", "Current stacks for fast, secure performance over the long term."]],
    steps: [["Discovery", "Discussing your needs, targets, and business goals to define the right solution."], ["Design", "Creating UI/UX aligned with your brand identity and user experience."], ["Development", "Coding with regular progress updates so you always know the status."], ["Testing", "Thorough testing across function, performance, and device compatibility."], ["Launch", "Your website or application goes live and is ready for users."], ["Support", "Post-launch guidance, maintenance, and ongoing technical help."]],
    plans: [["Try First", "Free", "first 7 weeks", "Try a website or landing page for seven weeks at no cost.", ["1-page website", "Responsive design", "7-week free trial", "No card / deposit"]], ["Starter", "Rp 298.000", "starting per project", "For landing pages or simple websites with basic needs.", ["1-3 pages", "Responsive design", "Domain & hosting", "Basic SEO"]], ["Business", "Contact Us", "based on needs", "For company profiles, e-commerce, or custom systems with complete features.", ["Multi-page / custom pages", "Database integration", "Admin panel/CMS", "Post-launch support"]]],
    faqs: [["How long does a website take?", "Landing pages usually take 3-7 days, company profiles 1-2 weeks, and custom systems 3-8 weeks."], ["Is there a warranty after launch?", "Yes, we provide free bug-fixing support for a defined period after launch."], ["How does payment work?", "30% upfront, then 70% after the project is complete and before launch."], ["Will the website be SEO optimized?", "Yes, every website includes on-page SEO basics such as loading speed, heading structure, and meta tags."], ["Do you serve clients outside Wonosobo?", "Yes, we serve clients across Indonesia remotely."], ["How do I start a project?", "Contact us through the form or WhatsApp for a free consultation."]],
    testimonials: [["Budi Santoso", "Owner, Retail Nusantara", "The ALW Gen team was responsive and the website exceeded our expectations."], ["Sari Wulandari", "Marketing Manager, Glow Skincare", "The landing page immediately improved our sales conversion."], ["Ahmad Fauzi", "Director, Konsultan Prima Advisory", "Clear process, smooth communication, and a result that matched our expectations."]],
  },
} as const;

export default function HomepageContent() {
  const { language } = useLanguage();
  const c = copy[language];
  const technologies = ["Next.js", "React", "Node.js", "PostgreSQL", "Tailwind CSS", "Vercel", "Cloudinary"];
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: c.faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <section className="alw-new-hero"><div className="alw-container"><span className="alw-badge">{c.badge}</span><h1>{c.title}</h1><p>{c.subtitle}</p><div className="alw-actions"><Link href="/contact" className="alw-btn alw-btn-primary">{c.primary} ↗</Link><Link href="/services" className="alw-btn alw-btn-ghost">{c.servicesCta}</Link></div><small>{c.location}</small><div className="alw-hero-cards" aria-label="Featured projects">{siteContent.heroCards.map((card, index) => <a key={card.title} href={card.link} target="_blank" rel="noopener noreferrer" className={`alw-hero-card ${card.big ? "alw-hero-card-big" : ""}`} style={{ backgroundImage: `url('${card.image}')` }} aria-label={`${c.portfolioCta}: ${card.title}`}><span>{card.title}</span></a>)}</div></div></section>
    <section className="alw-trust"><div className="alw-container"><div className="alw-stat-grid">{c.stats.map(([number, label]) => <div key={label}><strong>{number}</strong><span>{label}</span></div>)}</div><p>{c.trustTitle}</p></div></section>
    <section className="alw-section" id="services"><div className="alw-container"><SectionIntro title={c.servicesTitle} subtitle={c.servicesSub} /><div className="alw-card-grid">{c.services.map(([title, description], i) => <Link href="/services" className="alw-feature-card" key={title}><span className="alw-number">0{i + 1}</span><h3>{title}</h3><p>{description}</p><b>Explore service ↗</b></Link>)}</div></div></section>
    <section className="alw-section alw-soft" id="why-us"><div className="alw-container"><SectionIntro title={c.whyTitle} subtitle={c.whySub} /><div className="alw-card-grid alw-four">{c.reasons.map(([title, description], i) => <article className="alw-feature-card" key={title}><span className="alw-icon">0{i + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="alw-section" id="workflow"><div className="alw-container"><SectionIntro title={c.processTitle} subtitle={c.processSub} /><div className="alw-workflow">{c.steps.map(([title, description], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="alw-section alw-pricing" id="pricing"><div className="alw-container"><SectionIntro title={c.pricingTitle} subtitle={c.pricingSub} /><div className="alw-trial"><strong>{c.trialBanner}</strong><span>{c.trialNote}</span></div><div className="alw-card-grid">{c.plans.map(([name, price, note, description, features], i) => <article className={`alw-price-card ${i === 0 ? "alw-highlight" : ""}`} key={name}>{i === 0 && <em>Most Popular</em>}<small>{note}</small><h3>{name}</h3><strong>{price}</strong><p>{description}</p><ul>{features.map(feature => <li key={feature}>✓ {feature}</li>)}</ul><Link href="/contact" className="alw-btn alw-btn-primary">{i === 0 ? c.primary : "Choose package"} →</Link></article>)}</div></div></section>
    <section className="alw-section" id="portfolio"><div className="alw-container"><SectionIntro title={c.portfolioTitle} subtitle={c.portfolioSub} /><div className="alw-portfolio-note">Portfolio projects are loaded from the live collection.</div><Link href="/portfolio" className="alw-btn alw-btn-ghost">{c.portfolioCta} →</Link></div></section>
    <section className="alw-section alw-soft"><div className="alw-container"><SectionIntro title={c.testimonialsTitle} subtitle={c.testimonialsSub} /><div className="alw-card-grid">{c.testimonials.map(([name, role, quote]) => <article className="alw-quote" key={name}><div>★★★★★</div><p>“{quote}”</p><strong>{name}</strong><span>{role}</span></article>)}</div></div></section>
    <section className="alw-section"><div className="alw-container"><SectionIntro title={c.techTitle} subtitle={c.techSub} /><div className="alw-tech-list">{technologies.map(item => <span key={item}>{item}</span>)}</div></div></section>
    <section className="alw-section alw-about"><div className="alw-container"><div><SectionIntro title={c.aboutTitle} subtitle={c.aboutText} /><Link href="/about" className="alw-btn alw-btn-primary">{c.aboutCta} →</Link></div><div className="alw-blog"><SectionIntro title={c.blogTitle} subtitle={c.blogSub} /><span>{c.comingSoon}</span></div></div></section>
    <section className="alw-section alw-soft"><div className="alw-container"><SectionIntro title={c.faqTitle} /><div className="alw-faq">{c.faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
    <section className="alw-final"><div className="alw-container"><h2>{c.finalTitle}</h2><p>{c.finalSub}</p><div className="alw-actions"><Link href="/contact" className="alw-btn alw-btn-primary">{c.finalCta} ↗</Link><a href="https://wa.me/6285716275034" className="alw-btn alw-btn-ghost">{c.whatsapp}</a></div></div></section>
  </>;
}

function SectionIntro({ title, subtitle }: { title: string; subtitle?: string }) {
  return <div className="alw-section-intro"><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>;
}